spring:
  application:
    name: cloud-eureka-cqz22
eureka:
  client:


    register-with-eureka: false
    fetch-registry: false
    region: cq
    availability-zones:
      cq: z2,z1

    service-url:
      z1: http://localhost:7911/eureka/,http://localhost:7912/eureka/
      z2: http://localhost:7921/eureka/,http://localhost:7922/eureka/

    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000
      use-read-only-response-cache: false
      response-cache-update-interval-ms: 1000
server:
  port: 7922


