server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
    registry-fetch-interval-seconds: 1



  instance:
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
    hostname: localhost
    #true表示，将自己的ip注册到Eureka Server上，不配置或false表示将所在操作系统hostname注册到eureka server上。
    prefer-ip-address: false
    ip-address: 127.0.0.1
    instance-id: api-passenger

spring:
  application:
    name: api-passenger
  cloud:
    service-registry:
      auto-registration:
        enabled: true
